title: SOM
lang: es
remote_theme: rundocs/jekyll-rtd-theme

translate:
 search: buscar
 search_docs: buscar

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
