title: SOM
lang: es
remote_theme: rundocs/jekyll-rtd-theme

translate:
 note: info
 search: buscar
 search_docs: buscar..
 searching: buscando
 not_found: no_encontrado
 search_results_found: resultados_encontrados

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
